seed: 2025

data:
  sample_rate_hz: 50        # HAR sampling rate (Hz)
  window_size: 128          # samples per segment
  n_classes: 6              # activities (WALK, SIT, etc.)

features:
  stats: [mean, std, rms, mad, iqr, min, max, skew, kurt]
  bands: [[0.5, 3], [3, 8], [8, 15]]  # low/mid/high frequency bands

rf:
  n_estimators: 400
  max_depth: 30
  min_samples_leaf: 2
  class_weight: balanced
  n_jobs: -1

rnn:
  seq_len: 128
  hidden_size: 64
  n_layers: 1        
  dropout: 0.2       
  batch_size: 128
  epochs: 50
  lr: 0.001
  clip_norm: 1.0


eval:
  test_size: 0.2
  drift_alpha: 0.01
  psi_warn: 0.1
  psi_alert: 0.25
